/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora.combustivel;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author lab4l
 */
public class CALCULADORA extends javax.swing.JFrame {

    /**
     * Creates new form CALCULADORA
     */
    public CALCULADORA() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botao_sobre = new javax.swing.JLabel();
        botao_calcular = new javax.swing.JLabel();
        caixa_autonomia_etanol = new javax.swing.JTextField();
        caixa_autonomia_gasolina = new javax.swing.JTextField();
        label_resultado_preço_etanol = new javax.swing.JLabel();
        caixa_preco_etanol = new javax.swing.JTextField();
        label_resultado_preço_gasolina = new javax.swing.JLabel();
        label_economia = new javax.swing.JLabel();
        label_resultado_relaçao = new javax.swing.JLabel();
        label_abasteça = new javax.swing.JLabel();
        caixa_preco_gasolina = new javax.swing.JTextField();
        FUNDO = new javax.swing.JLabel();
        botao_calcular1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 780));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 555, 100, 95));

        botao_sobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_sobreMouseClicked(evt);
            }
        });
        getContentPane().add(botao_sobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 660, 100, 20));

        botao_calcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_calcularMouseClicked(evt);
            }
        });
        getContentPane().add(botao_calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 555, 100, 95));

        caixa_autonomia_etanol.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        caixa_autonomia_etanol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixa_autonomia_etanolActionPerformed(evt);
            }
        });
        getContentPane().add(caixa_autonomia_etanol, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 200, 50));

        caixa_autonomia_gasolina.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        caixa_autonomia_gasolina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixa_autonomia_gasolinaActionPerformed(evt);
            }
        });
        getContentPane().add(caixa_autonomia_gasolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 200, 50));

        label_resultado_preço_etanol.setFont(new java.awt.Font("Digital-7", 3, 40)); // NOI18N
        getContentPane().add(label_resultado_preço_etanol, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 200, 35));

        caixa_preco_etanol.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(caixa_preco_etanol, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 200, 50));

        label_resultado_preço_gasolina.setFont(new java.awt.Font("Digital-7", 3, 40)); // NOI18N
        getContentPane().add(label_resultado_preço_gasolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 200, 35));

        label_economia.setFont(new java.awt.Font("Digital-7", 3, 36)); // NOI18N
        label_economia.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(label_economia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 430, 40));

        label_resultado_relaçao.setFont(new java.awt.Font("Digital-7", 3, 40)); // NOI18N
        getContentPane().add(label_resultado_relaçao, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 200, 35));

        label_abasteça.setFont(new java.awt.Font("Digital-7", 3, 36)); // NOI18N
        label_abasteça.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(label_abasteça, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 430, 40));

        caixa_preco_gasolina.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        caixa_preco_gasolina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixa_preco_gasolinaActionPerformed(evt);
            }
        });
        getContentPane().add(caixa_preco_gasolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 200, 50));

        FUNDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/combustivel/calculadora finish 56.png"))); // NOI18N
        getContentPane().add(FUNDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        botao_calcular1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_calcular1MouseClicked(evt);
            }
        });
        getContentPane().add(botao_calcular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, 100, 95));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void caixa_autonomia_gasolinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixa_autonomia_gasolinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixa_autonomia_gasolinaActionPerformed

    private void caixa_preco_gasolinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixa_preco_gasolinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixa_preco_gasolinaActionPerformed

    private void caixa_autonomia_etanolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixa_autonomia_etanolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixa_autonomia_etanolActionPerformed

    private void botao_calcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_calcularMouseClicked
        
        String precogasolinaStr = caixa_preco_gasolina.getText();
        String precoetanolStr = caixa_preco_etanol.getText();
        String autogasolinaStr = caixa_autonomia_gasolina.getText();
        String autoetanolStr = caixa_autonomia_etanol.getText();
        
        //CONVERÇÃO PARA NUMERO
        
        
         if (precoetanolStr.isEmpty() || precogasolinaStr.isEmpty() || autoetanolStr.isEmpty() || autogasolinaStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencher todos os campos!");
            return;
        }

        double autogasolina, precogasolina , precoetanol, autoetanol;
        
        try {
            precoetanol = Double.parseDouble(precoetanolStr);
            precogasolina = Double.parseDouble(precogasolinaStr);
            autogasolina = Double.parseDouble(autogasolinaStr);
            autoetanol = Double.parseDouble(autoetanolStr);
            
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Coloque valores válidos!");
            return;
        }
        
        
        //CONTAS
        
        double relacao = (precoetanol / precogasolina)*100;
        double resultadoetanol = (precoetanol / autoetanol);
        double resultadogasolina = (precogasolina / autogasolina);
        
        if (resultadoetanol == resultadogasolina){
            
            label_abasteça.setText("Mesmo custo!");
            label_economia.setText("");
        }else{
        
        if (resultadoetanol > resultadogasolina){
            double resultadoeconomia = resultadoetanol-resultadogasolina; 
            String resultadoeconomiaStr = String.format("Economia de %.2f por KM",resultadoeconomia);
            label_abasteça.setText("Abasteça com Gasolina!");
            label_economia.setText(resultadoeconomiaStr);
        }else{
            double resultadoeconomia = resultadogasolina-resultadoetanol;
            String resultadoeconomiaStr = String.format("Economia de %.2f por KM",resultadoeconomia);
            label_abasteça.setText("Abasteça com Etanol!");
            label_economia.setText(resultadoeconomiaStr);
        }            
        }
               
              
        //CONVERSÃO PARA TEXTO
        
        String relacaoStr = String.format("%.0f %% ",relacao);
        String resultadoetanolStr = String.format("R$ %.2f",resultadoetanol);
        String resultadogasolinaStr = String.format("R$ %.2f",resultadogasolina);

        
        //PRINT
        
        label_resultado_relaçao.setText(relacaoStr);
        label_resultado_preço_gasolina.setText(resultadogasolinaStr);
        label_resultado_preço_etanol.setText(resultadoetanolStr);
        
        //

        
        
    }//GEN-LAST:event_botao_calcularMouseClicked

    private void botao_sobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_sobreMouseClicked
       
        new sobre ().setVisible(true);
    }//GEN-LAST:event_botao_sobreMouseClicked

    private void botao_calcular1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_calcular1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_calcular1MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
        label_abasteça.setText("");
        label_resultado_preço_gasolina.setText("");
        label_resultado_preço_etanol.setText("");
        label_economia.setText("");
        label_resultado_relaçao.setText("");
        caixa_autonomia_etanol.setText("");
        caixa_autonomia_gasolina.setText("");
        caixa_preco_etanol.setText("");
        caixa_preco_gasolina.setText("");
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CALCULADORA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CALCULADORA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CALCULADORA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CALCULADORA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CALCULADORA().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FUNDO;
    private javax.swing.JLabel botao_calcular;
    private javax.swing.JLabel botao_calcular1;
    private javax.swing.JLabel botao_sobre;
    private javax.swing.JTextField caixa_autonomia_etanol;
    private javax.swing.JTextField caixa_autonomia_gasolina;
    private javax.swing.JTextField caixa_preco_etanol;
    private javax.swing.JTextField caixa_preco_gasolina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_abasteça;
    private javax.swing.JLabel label_economia;
    private javax.swing.JLabel label_resultado_preço_etanol;
    private javax.swing.JLabel label_resultado_preço_gasolina;
    private javax.swing.JLabel label_resultado_relaçao;
    // End of variables declaration//GEN-END:variables
}
